CREATE TABLE IF NOT EXISTS PERSON  (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    PRENOM VARCHAR(20) NOT NULL,
    NOM VARCHAR(20),
    METIER VARCHAR(20),
    ADRESSE VARCHAR(255),
    PRIMARY KEY(ID)
    ) ENGINE=InnoDB;